### ISSUE TITLE
OSX Python 2.6 Stops AppEngine Launcher but system reports 2.7.6 installed

### ISSUE THREAD

**Issue by shaneholloman** [GoogleCloudPlatform/appengine-php-wordpress-starter-project#15]
`rocketadmin at rocket in ~
$ python --version
Python 2.7.6`

FROM CONSOLE
*** Running dev_appserver with the following flags:
    --skip_sdk_update_check=yes --port=8080 --admin_port=8000
Python command: /usr/bin/python2.7
Error: Python 2.6 is not supported. Please use version 2.7.

But FROM TERMINAL
`which python`
/Library/Frameworks/Python.framework/Versions/2.7/bin/python

If I `cat ~/.bash_profile`
PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:${PATH}"

I have sourced my profile, restarted - I'm stuck at this point
What steps do I take remedy this?

**Comment by johndmulhausen** [comment]
Really not sure, but honestly, this is not an issue with the sample.
