### ISSUE TITLE
css not load in wp-admin

### ISSUE THREAD

**Issue by Snake231088** [GoogleCloudPlatform/appengine-php-wordpress-starter-project#17]
In wp-admin ( in backend ) the css not load because there is a function that get content through 'realpath', that in app engine is not supported, so js and css not load correctly.
I try to fix by adding a little block of code.

**Comment by johndmulhausen** [comment]
No repro, sorry. Feel free to reopen if this continues.

**Comment by naeemshah** [comment]
having same issue

**Comment by aquilesb** [comment]
Just add this code in your app.yaml as the first url handle and it should works

```
- url: /wp/(.*\.(htm|html|css|js|svg))$
  static_files: wordpress/\1
  upload: wordpress/.*\.(htm|html|css|js|svg)$
  application_readable: true
```
