### ISSUE TITLE
Write a Google Compute Engine startup script to make WP app engine deployment easier 

### ISSUE THREAD

**Issue by kimasaki** [GoogleCloudPlatform/appengine-php-wordpress-starter-project#19]
I wrote GCE startup script (http://storage.googleapis.com/wordpress123/wa.sh) to make deployment easier based on this document. With this script, you can start VM on GCE like the following 
gcutil addinstance wordpressintance --metadata=project_id:xxxx --metadata=sql_pwd:xxxx --metadata=startup-script-url:http://storage.googleapis.com/wordpress123/wa.sh

Once the startscript finishes executing, everything is ready. Do you think it is useful to be checked in?

**Comment by johndmulhausen** [comment]
We now have Click-to-Deploy WordPress for Compute Engine, so that makes this issue a bit redundant. Check it out at cloud.google.com/launcher.
