### ISSUE TITLE
Builds - Wordpress version & other inconsistencies

### ISSUE THREAD

**Issue by euene** [GoogleCloudPlatform/appengine-php-wordpress-starter-project#22]
The Wordpress version included in the build for Windows is 4.0-alpha(?), also the Mac build is using the old 3.8.1.

Can we please get both builds updated with the latest stable release (3.9.1)?

There is also an inconsistency with the Windows build, the archive's contents being in a folder called "wp39 - Copy" instead of one with a more appropriate name.

It's also missing the readme file that's present in the Mac archive.

On a similar note of folders/directory structure, wouldn't it also be better if the contents of the App Engine plug-in are in their own folder instead of sitting in the root of wp-content/plugins ? 

It looks much cleaner this way, especially once you start adding more plug-ins.

**Comment by johndmulhausen** [comment]
Obsolete bug.
