### ISSUE TITLE
Avada Google App Engine - PLUGIN Installation issue

### ISSUE THREAD

**Issue by rcotgrov** [GoogleCloudPlatform/appengine-php-wordpress-starter-project#26]
Using the local installation; I've installed the Avada theme without issue but then it prompts for required plugins

*****
This theme requires the following plugin installed or update: Fusion Core.
This theme recommends the following plugin installed or updated: Revolution Slider.
Begin installing plugins | Dismiss this notice

****

Clicking Begin installing plugins directs to this page and it throws an error

http://localhost:8080/wp-admin/themes.php?page=install-required-plugins

You do not have sufficient permissions to access this page.
 

I have tried all the usual checks and even re-installed a fresh copy of WordPress 3.9.1 from  your ZIP file and a blank database and then installed the theme again. It even happens when doing this so something is very odd about the theme installation and the Google App Engine.

The theme authors believe the issue is one of the hosting environment and security, e.g something strange about the WAMP type setup etc...  

Thoughts anyone ?

**Comment by johndmulhausen** [comment]
No updates in some time. If the issue was not fixed by that SDK release, let us know!
