### ISSUE TITLE
Problems with the MySQL command line tool

### ISSUE THREAD

**Issue by FKrauss** [GoogleCloudPlatform/appengine-php-wordpress-starter-project#27]
I had this problem and solved it, so I just wanted to put it here for people to have a visibility on it.

I followed all the steps on deploying the app to App Engine but it would never work to create the wordpress_db database via the MySQL console.

I found out two problems:
1) the *google_sql.py* script uses a method that is not supported anymore, so you have to create the database yourself.
2) there can be mismatches between the MySQL versions you use. If you, like me, downloaded MySQL just for this project, you'll download the **5.6** version and usually the SQL instance you create on Google's Cloud is set to **5.5** by default. Besides that the command in the documentation didn't work, the console returned an error message saying the sintax was wrong. I'm not familiar with this language to pinpoint the mistake but what did work was to open the MySQL connection wizard and add the root password and Address of the Cloud SQL instance there. It connected fine and to run the 

   CREATE DATABASE IF NOT EXISTS wordpress_db;

Command you can just open a script for querying and run it from there.

Besides this, it all ran fine =)

And a little warning: make sure you don't forget the initial password you add to wordpress while first accessing it, the installation you now have does not have the mail functionalities enabled and the root password does not give you access to the front-end ;)

**Comment by johndmulhausen** [comment]
Obsolete; we now ask people not to use google_sql.py which is deprecated, and use MySQL directly, which will run CREATE DATABASE IF NOT EXISTS wordpress_db; no prob.
