### ISSUE TITLE
Font awesome fonts fail to load properly for wordpress

### ISSUE THREAD

**Issue by jpbetz** [GoogleCloudPlatform/appengine-php-wordpress-starter-project#28]
I found that when using this wordpress starter project that font awesome fonts,  which are used by a lot of themes,  fail to load.

I was able to fix by adding the following to my app.yaml file:

- url: /(.*\.(eot|svg|ttf|woff))$
  static_files: wordpress/\1
  upload: wordpress/.*\.(eot|svg|ttf|woff)$
  application_readable: true

**Comment by johndmulhausen** [comment]
woff|ttf|otf|eot|svg added to app.yaml
