### ISSUE TITLE
Font mimetypes not supported/detected on GAE

### ISSUE THREAD

**Issue by ikeralbeniz** [GoogleCloudPlatform/appengine-php-wordpress-starter-project#30]
Please add font mimetype detection on app.yaml

\- url: /wp-content/(.\*\\.ttf)$
  static_files: wordpress/wp-content/\1
  upload: wordpress/wp-content/.\*\\.ttf$
  mime_type: application/x-font-ttf

\- url: /wp-content/(.\*\\.otf)$
  static_files: wordpress/wp-content/\1
  upload: wordpress/wp-content/.\*\\.otf$
  mime_type: application/x-font-otf

\- url: /wp-content/(.\*\\.woff)$
  static_files: wordpress/wp-content/\1
  upload: wordpress/wp-content/.\*\\.woff$
  mime_type: application/x-font-woff

**Comment by onofrioP89** [comment]
Any news for this problem?
Thank you
Onofrio

**Comment by johndmulhausen** [comment]
Added woff|ttf|otf to app.yaml. Thanks!
