### ISSUE TITLE
When updating to wp 4.0 media upload trows http error

### ISSUE THREAD

**Issue by Rovel** [GoogleCloudPlatform/appengine-php-wordpress-starter-project#33]
I was trying to update this project since all plugins and wp itself have new versions.

I simply changed the wp folder to the new version with batcache and GAE plugin in its folders.

After that I changes the wp-config.php to match the DB config settings for CloudSQL and project ID to wp-config.php and app.yaml

Everything works fine in wp-admin, except that the media file is uploaded to the bucket, but instead of  showing the files in the media list, at the end of the upload the wp-admin says that was an http error.

Does someone knows what it may be? one time debug sayd that the app had a problem with batcache, but I'v just followed all the configs in batcache installation. Is there a special config for batcache in this GAE-wp project?

**Comment by johndmulhausen** [comment]
Submodule updated. Thanks!
