### ISSUE TITLE
Activating CURL

### ISSUE THREAD

**Issue by ashraf13** [GoogleCloudPlatform/appengine-php-wordpress-starter-project#37]
Hi,
I'm looking to activate CURL can you help me with that please
Thanks

**Comment by syswperu** [comment]
CURL is not allowed for GAE, you can use urlfetch (https://developers.google.com/appengine/docs/php/urlfetch/)

**Comment by uncelestial** [comment]
Here ya go!
https://cloud.google.com/appengine/docs/php/#dynamically_loadable_extensions

**Comment by johndmulhausen** [comment]
Here ya go!
https://cloud.google.com/appengine/docs/php/#dynamically_loadable_extensions
