### ISSUE TITLE
Using wordpress in GAE free tier

### ISSUE THREAD

**Issue by LeonidVasilyev** [GoogleCloudPlatform/appengine-php-wordpress-starter-project#39]
As I understand MySql is unavailable in free tier, is it possible to substitute it with available database or use some external storage to use wordpress in free tier?

**Comment by johndmulhausen** [comment]
It probably would be quite slow, but sure! Keep in mind that for non-Cloud-SQL MySQL connections will not keep a persistent connection (the MySQL connection will be torn down after each request). You would get much better performance installing MySQL on Compute Engine, but that too is a paid product. Interesting use case. Not officially supported, but we think it's technically possible. :)
