### ISSUE TITLE
port!=80 and networked/multi-user sites?

### ISSUE THREAD

**Issue by alfredwb** [GoogleCloudPlatform/appengine-php-wordpress-starter-project#48]
I'd love to run Wordpress MU (networked, multi site), but when I try and enable it, I get warned that it won't work (on my local copy) as I'm not running on port 80. 
I can't seem to start AppEngineLauncher on port 80, even though there are no other port 80 listeners on my mac.
Any suggestions?

**Comment by Trii** [comment]
You cannot use the launcher to start on a privileged port. You have to use dev_appserver.py via command line.

**Comment by alfredwb** [comment]
Thanks!
