### ISSUE TITLE
Repository directory structure for OSX

### ISSUE THREAD

**Issue by shaneholloman** [GoogleCloudPlatform/appengine-php-wordpress-starter-project#7]
My project name is: `ultrapressor`
so I `gcloud init ultrapressor`
I now have this dir:
 ~/google-cloud-sdk/ultrapressor

Inside is already a `default` dir

Should the contents of your repository go inside `default` with the `.git` folder like so:
 ~/google-cloud-sdk/ultrapressor/default/
.git
app.yaml
cron.yaml
php.ini
wordpress

I'm not clear of the correct directory structure that should happen here so
1. I can deploy to production
2. Have a clean https://source.developers.google.com/p/ultrapressor/ folder
I bring this up as my last repo from 8 months showed in the console but would not `init` or `pull`

Thanks all...

**Comment by johndmulhausen** [comment]
Yep, that's the idea. The app.yaml goes in the root.
