### ISSUE TITLE
Could not create directory for the new theme installation

### ISSUE THREAD

**Issue by marsinearth** [GoogleCloudPlatform/appengine-php-wordpress-starter-project#78]
I've done putting define('FS_METHOD', 'direct'); and define('WP_SITEURL', 'http://localhost:8080/');
to both wp-config.php of the root directory of the project and one inside of the wordpress directory. 
Also did chmod -R 755 wordpress/wp-content but no luck.. I'm trying it with the local drive on my mac.

**Comment by daron4ever** [comment]
You don't need to edit wp-config. Just copy your new theme into theme folder.
